### ISSUE TITLE
High Sierra compatibility?

### ISSUE THREAD

**Issue by tholu** [AlmirKadric-Published/docker-tuntap-osx#2]
Will this be compatible with macOS High Sierra? Apple seems to be limiting usage of kernel extensions.

**Comment by AlmirKadric** [comment]
The support of High Sierra will be completely dependent on the compatibility of the TunTap brew cask package. When Sierra was released the TunTap brew formulae was moved from Brew (compiled on install) to Brew Cask (pre-compiled and signed) so that Sierra would stop complaining about the kernel extension not being signed. Worst case scenario, the maintainers of the TunTap package will have patch the extension to play well with the new user authentication system (if it doesn't work out of the box). However other Kernel Extension restrictions should be fine (if anyone knows better feel free to correct me).

Edit: From what I have read about other kernel extensions, there is a popup shown when the user attempts to load the kernel extensions. Provided they hit yes, it should work:
https://forums.developer.apple.com/thread/79172

**Comment by tholu** [comment]
@AlmirKadric Thanks for the fast answer & clarification!
